package camilonko.metelasmanos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label(value = "edad")
   private java.lang.Integer edad;
   @org.kie.api.definition.type.Label(value = "sexo")
   private java.lang.String sexo;

   public Persona()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(java.lang.String sexo)
   {
      this.sexo = sexo;
   }

   public Persona(java.lang.String nombre, java.lang.Integer edad,
         java.lang.String sexo)
   {
      this.nombre = nombre;
      this.edad = edad;
      this.sexo = sexo;
   }

}