package camilonko.metelasmanos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label("edad")
   private java.lang.Integer edad;
   @org.kie.api.definition.type.Label("sexo")
   private java.lang.String sexo;

   @org.kie.api.definition.type.Label("estadoCivil")
   private java.lang.String estadoCivil;

   @org.kie.api.definition.type.Label(value = "flag")
   private java.lang.Boolean flag;

   public Persona()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(java.lang.String sexo)
   {
      this.sexo = sexo;
   }

   public java.lang.String getEstadoCivil()
   {
      return this.estadoCivil;
   }

   public void setEstadoCivil(java.lang.String estadoCivil)
   {
      this.estadoCivil = estadoCivil;
   }

   public java.lang.Boolean getFlag()
   {
      return this.flag;
   }

   public void setFlag(java.lang.Boolean flag)
   {
      this.flag = flag;
   }

   public Persona(java.lang.String nombre, java.lang.Integer edad,
         java.lang.String sexo, java.lang.String estadoCivil,
         java.lang.Boolean flag)
   {
      this.nombre = nombre;
      this.edad = edad;
      this.sexo = sexo;
      this.estadoCivil = estadoCivil;
      this.flag = flag;
   }

}